function crowdingInstructions(currBlock, w)

%==============================================================
% Adapted from Dan's displayInstructions.m
%==============================================================
grey = GrayIndex(w,0.5);
Screen('FillRect', w, grey);
Screen('TextSize', w, []);

instText = [];

%Practice Instructions
if currBlock == 0 
    instText = ['Each trial will begin with a fixation cross, after which\n'...
        'some striped circles will appear, either as a single circle or\n'...
         'in an arrangement of 6 flanking circles and a central circle. \n\n'...
        'Either the single circle or the central circle is your target.\n\n'...
        'If the target is tilted to the RIGHT (stripes aligned with "/"), \n'...
        'press the RIGHT ARROW KEY. \n\n'...
        'If the target is tilted to the LEFT (stripes aligned with "\"), \n'...
        'press the LEFT ARROW KEY. \n\n\n\n'...
        'You have a limited time to respond; if you do not respond quickly\n'...
        'enough, it will count as incorrect.\n\n\n'...
        'If you respond on time, you will hear a beep. \n\n'...
        'If you run out of time, you will hear a higher beep. \n\n\n'...        
        'We will start with some practice trials. \n\n'...
        'Press any key to continue.'];
elseif currBlock == 1
    instText = ['The practice block is now complete.\n\n'...
                'There will be a number of experimental blocks with breaks in between.\n\n'...                
                'Press any key to continue.\n\n'];
else
    instText = 'Press any key to continue.\n\n';
end
DrawFormattedText(w, instText, 'Center', 'Center', [255 255 255]);

Screen('Flip', w);
FlushEvents('keyDown');
GetChar;
Screen('TextSize', w, 20);
Screen('Flip', w);

